### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
#   See COPYING file distributed along with the MGTAXA package for the
#   copyright and license terms.
#
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##


from MGT.Kmers import *
from MGT.Common import *

kmerLen = 4

#seqStr = "aaaaaaccccccccccggggggggggggttttttttttttttt".upper()

seqStr = ''.join([
"GATCTTACCCTCAAATATTATTAATCTACGACTATAAAGCTAACAATCCTTAAAAAGCTTGTCAATTTTTACTCTAAATA",
"ATAAAATCATAATTAACCAAAAACAAACTCTAAGAAGGAGGAGGAAAAATGAGTAAAATGCGTATTGGTGTATTAACAGG",
"TGGAGGCGATTGCCCAGGTCTAAACCCAGCTATCCGTGGTATTGTCATGAGAGCATTAGATTATGGAGACGAAGTTATAG",
"GTTTGAAGTATGGATGGGCTGGTCTTCTTAAGGCAGATACTATGCCTTTATCCTTAGAAATGGTAGAAGATATTCTTGAA",
"ATCGGCGGAACAATTCTTGGAAGTTCTAGAACAAACCCATTCAAAAAAGAAGAAGATGTTCAAAAATGTGTTGAGAACTT",
"CAAAAAGTTAAACTTAGATGCCTTAATCGCCATAGGTGGAGAAGACACTCTAGGAGTTGCATCAAAATTTAGCAAACTTG",
"GTCTTCCAATGATCGGAGTTCCAAAAACTATTGATAAAGATTTAGAAGAAACTGACTATACTCTTGGATTTGACACTGCT",
"GTTGAAGTAGTGGTAGATGCAATTAAAAGACTTAGAGATACTGCAAGATCTCATGCAAGAGTTATCGTAGTAGAAATAAT",
"GGGAAGACATGCAGGATGGTTAGCTCTTTATGGTGGGCTTGCAGGAGGAGCAGATTATATCTTAATCCCTGAAGTAGAAC",
"CTAATCTTGAGGATCTTTACAATCACATAAGAAAACTATACGCAAGAGGAAGAAATCACGCAGTTGTAGCCATCGCTGAG",
"GGAGTACAACTACCAGGATTTACTTATCAAAAAGGACAAGAAGGAATGGTAGATGCCTTTGGTCACATTCGCTTAGGTGG",
"TGTAGGTAATGTACTAGCCGAAGAGATACAGAAGAACTTGGGAATTGAAACCAGAGCCGTAATCTTAAGCCACCTACAAA",
"GGGGAGGAAGTCCATCAATAAGAGATAGAATCATGGGGCTTCTCCTTGGTAAGAAGGCTGTAGACTTAGTACATGAAGGA"
])

seq = n.fromstring(seqStr,dtype="S1")

print seqStr

counter = KmerLadderSparseFeatures(len(seq)*2,kmerLen)

feature = counter.kmerFrequencies(seq)

print feature

